name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore Build.Puffix.Exceptions.sln 
    - name: Build
      run: dotnet build Build.Puffix.Exceptions.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Build.Puffix.Exceptions.sln --no-restore --verbosity normal
    - name: Publish Nuget Package on Nuget
      run: dotnet nuget push /home/runner/work/Puffix.Exceptions/Puffix.Exceptions/Puffix.Exceptions/bin/Release/Puffix.Exceptions.2.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
